#Ansible "site.yml" file.
#Specifies the configuration of hosts
#
#end state: all webservers configured with the webserver ROLE
#
#apache servers
- hosts: webservers 
  become: true
  become_method: sudo

  roles:
  - { role: webserver }

#flask servers
- hosts: flaskservers
  become: true
  become_method: sudo

  roles:
  - { role: flaskserver }

# do not do DNS automation yet..
#- hosts: dns
# become: true
# become_method: sudo
#
#  roles:
#  - { role: dns }
