#Ansible "site.yml" file.
#Specifies the configuration of hosts
#
#end state: all webservers configured with the webserver ROLE
#
#apache servers
- hosts: webphpservers 
  become: true
  become_method: sudo

  roles:
  - { role: webphpserver }

